name: Docker Image

on:
  schedule:
    - cron: "0 10 * * *" # everyday at 10am
  push:
    branches: ["**"]
    tags: ["v*.*.*"]

env:
  platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6

jobs:
  main:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set imageName based on the repository name
        id: step_one
        run: |
            imageName="${GITHUB_REPOSITORY/docker-/}"
            echo $imageName
            echo "imageName=$imageName" >> $GITHUB_ENV
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.imageName }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Buildx cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-docker-${{ hashfiles('cache/**') }}
          restore-keys: |
            ${{ runner.os }}-docker
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ env.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=${{ github.workspace }}/cache
          cache-to: type=local,dest=${{ github.workspace }}/cache
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.imageName }}:${{ steps.docker_meta.outputs.version }}
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
